---
resources:
  - ../base
  - hardware-profile.yaml
  - odh-document.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: dsci-cr.yaml
  - path: dsc-cr.yaml
  - path: odh-dashboard.yaml
  - path: mlflow.yaml

